export const FINANCIAL_STATEMENTS_COUNT = 8;
export const MODELING_PREP_CURRENT_PRICES_CHUNK_SIZE = 50;
export const MODELING_PREP_HISTORIC_PRICES_CHUNK_SIZE = 5;
export const MODELING_PREP_INCOME_STATEMENT_CHUNK_SIZE = 3;

// Timeouts
export const FETCH_SLEEP_TIMEOUT_MS = 50;
export const POSTGRES_SLEEP_TIMEOUT_MS = 50;

// New Stocks
export const NEW_STOCKS: string[] = [];
