CREATE TABLE income_statements (
    symbol VARCHAR(6),
    date DATE,
    revenue DOUBLE PRECISION,
    revenue_growth REAL,
    cost_of_revenue DOUBLE PRECISION,
    gross_profit DOUBLE PRECISION,
    rd_expense DOUBLE PRECISION,
    sga_expense DOUBLE PRECISION,
    operating_expense DOUBLE PRECISION,
    operating_income DOUBLE PRECISION,
    interest_expense DOUBLE PRECISION,
    ebt DOUBLE PRECISION,
    income_tax_expense DOUBLE PRECISION,
    net_income_non_controlling DOUBLE PRECISION,
    net_income_discontinued DOUBLE PRECISION,
    net_income DOUBLE PRECISION,
    preferred_dividends DOUBLE PRECISION,
    net_income_com DOUBLE PRECISION,
    eps REAL,
    eps_diluted REAL,
    shares_outstanding DOUBLE PRECISION,
    shares_outstanding_diluted DOUBLE PRECISION,
    dividend_per_share REAL,
    gross_margin REAL,
    ebitda_margin REAL,
    ebit_margin REAL,
    profit_margin REAL,
    free_cash_flow_margin REAL,
    ebitda DOUBLE PRECISION,
    ebit DOUBLE PRECISION,
    consolidated_income DOUBLE PRECISION,
    ebt_margin REAL,
    net_profit_margin REAL,
    PRIMARY KEY(symbol, date)
);
