CREATE TABLE recent_financials (
    symbol VARCHAR(6),
    revenue_8 DOUBLE PRECISION,
    revenue_7 DOUBLE PRECISION,
    revenue_6 DOUBLE PRECISION,
    revenue_5 DOUBLE PRECISION,
    revenue_4 DOUBLE PRECISION,
    revenue_3 DOUBLE PRECISION,
    revenue_2 DOUBLE PRECISION,
    revenue_1 DOUBLE PRECISION,
    gross_profit_8 DOUBLE PRECISION,
    gross_profit_7 DOUBLE PRECISION,
    gross_profit_6 DOUBLE PRECISION,
    gross_profit_5 DOUBLE PRECISION,
    gross_profit_4 DOUBLE PRECISION,
    gross_profit_3 DOUBLE PRECISION,
    gross_profit_2 DOUBLE PRECISION,
    gross_profit_1 DOUBLE PRECISION,
    op_income_8 DOUBLE PRECISION,
    op_income_7 DOUBLE PRECISION,
    op_income_6 DOUBLE PRECISION,
    op_income_5 DOUBLE PRECISION,
    op_income_4 DOUBLE PRECISION,
    op_income_3 DOUBLE PRECISION,
    op_income_2 DOUBLE PRECISION,
    op_income_1 DOUBLE PRECISION,
    net_income_8 DOUBLE PRECISION,
    net_income_7 DOUBLE PRECISION,
    net_income_6 DOUBLE PRECISION,
    net_income_5 DOUBLE PRECISION,
    net_income_4 DOUBLE PRECISION,
    net_income_3 DOUBLE PRECISION,
    net_income_2 DOUBLE PRECISION,
    net_income_1 DOUBLE PRECISION,
    PRIMARY KEY(symbol)
);
